sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

after_success:
  - if [ $(echo "${TRAVIS_NODE_VERSION}" | cut -d'.' -f1) -ge 4 ]; then
      npm run coveralls;
    fi

os:
  - linux
  - osx
